class SateliteDomainError(Exception):
    ...

class BateriaInsuficienteError(SateliteDomainError):
    ...

class TransicaoInvalidaError(SateliteDomainError):
    ...

class AtributosError(SateliteDomainError):
    ...